### ISSUE TITLE
JSON minify (combine remove all line breaks and trim spaces)

### ISSUE THREAD

**Issue by holyspidoo** [krasa/StringManipulation#117]
I can't find a way to minify JSON files in jetbrains products. All the plugins work with a separate windows, not the actual document.

Right now, I use your plugin but I have to use 2 steps:
1. Remove All new lines
2. Trim all spaces

It would be nice to have an option that does both in that order, so we can map it to a hotkey. 

(CTRL-ALT-L turns back JSON to pretty form)

**Comment by krasa** [comment]
You could probably make a macro. But the problem is that it is not right, you need a json library to do it properly.

This looks good: https://stackoverflow.com/a/42170511 with a small 68kB dependency, hopefully it is not bugged.

You can try it: https://github.com/krasa/StringManipulation/releases/download/8.9.191.000.0/StringManipulation.zip

**Comment by mcxinyu** [comment]
Hello, I want this feature too, and can you add support for other formats, such as XML, JS, etc

**Comment by mcxinyu** [comment]
> Hello, I want this feature too, and can you add support for other formats, such as XML, JS, etc

I find a new way.
```
idea -> Edit -> Join Lines
```
![image](https://user-images.githubusercontent.com/9566116/103716981-4a7ea280-4fff-11eb-947d-829723509413.png)


I think it works.
