### ISSUE TITLE
Feature Request: Basic UPPER and lower

### ISSUE THREAD

**Issue by Tecktron** [krasa/StringManipulation#44]
Thanks for the great plugin, however there are 2 basic things I'm always trying to go for in the context menu and they are:
- a basic convert to upper case: converts all the selected text to UPPER CASE, no matter what
- a basic convert to lower case: converts all the selected text to lower case, no matter what.

Examples: (input, function, output)
`Hello` -> UPPER -> `HELLO`
`Hello` -> lower -> `hello`
`TesT 12_34` -> UPPER -> `TEST 12_34`
`TesT 12_34` -> lower -> `test 12_34`

Cheers!

**Comment by krasa** [comment]
I think it's waste of space, since it is easier and faster to just press ctrl+shift+U (Editor Actions | Toggle Case).
But since so many people want this, I might as well do it.

**Comment by funivan** [comment]
Just use hotkeys ;)

![peek 2017-11-16 08-38](https://user-images.githubusercontent.com/425208/32877293-799c78b4-caa9-11e7-9c84-6c1731e9928c.gif)

**Comment by wilkolazki** [comment]
Built-in toggle case is not perfect. It requires you to think about the result. 
The result is different depending on the existence of any capital letter in edited string. If the string contains at least one capital letter it will be lowercased, and uppercased otherwise. In first case, you need to repeat the stroke to uppercase the string. 

The result is not deterministic in macros and cannot be used as no-brainer, because sometimes it requires two repeats and sometimes one is enough to uppercase something.

If there was option to always uppercase and another one to always lowercase, I would be glad to replace Ctrl+Shift+U with string manipulation shortcut. 
Just use [U] for uppercase second stroke and [L] for lowercase.

**Comment by mainsight** [comment]
> Built-in toggle case is not perfect. It requires you to think about the result.
Absolutely agreed. It will much better to use this feature inside string manipulations addon instead of built-in feature. Dear @krasa please implement it, we really need that.

**Comment by manuscle** [comment]
I agree too to add this basic feature!
