### ISSUE TITLE
Support Sublime Text Style Multiple Selections

### ISSUE THREAD

**Issue by Mincol** [krasa/StringManipulation#65]
When In Idea I multiselect and the use StringManipulation only one string is converted.
As a user I want to all selected strings to be converted.

Sublime Text Style Multiple Selections: https://blog.jetbrains.com/idea/2014/03/intellij-idea-13-1-rc-introduces-sublime-text-style-multiple-selections/

**Comment by krasa** [comment]
Which action?

**Comment by klass-ivan** [comment]
The same issue is highly-desired and "up-voted" by me.
The multi-selection is a feature natively supported by Idea, by default you may add another cursor by clicking Alt+Shift+`<MouseClick>`
![multiselection_foo](https://user-images.githubusercontent.com/2673108/52706707-9f9f0e80-2fb8-11e9-9fae-bff8ba27bd11.png)
@krasa the problem is you can't apply string action on all the selection, only a single one is processed.
Probably the issue is that multiselection is dropped once you right-click, so maybe plugin is unable to obtain all the selections in that case

**Comment by krasa** [comment]
There might be some actions that do not work right with multiselection - if you use a menu or shortcut, not right click. 
But if OP is using right click, then sure. IDE issue, nothing I can do. 🤣
